# Generated by Django 5.2.1 on 2025-11-15 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sport'),
        ('team', '0002_agegroup_alter_team_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.sport'),
        ),
    ]
