# Generated by Django 5.2.1 on 2025-11-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_cashier_penalty_assignedpenalty_team_tabel_h4a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Game_Plan_H4A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingebetteter_code', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
