# Generated by Django 5.2.1 on 2025-11-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
