# Generated by Django 5.2.1 on 2025-11-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('available_slots', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
