# Generated by Django 5.2.1 on 2025-11-13 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('venue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('competition', models.CharField(blank=True, max_length=255)),
                ('round', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='scheduled', max_length=30)),
                ('result_home', models.IntegerField(blank=True, null=True)),
                ('result_away', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='team.team')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='team.team')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matches', to=settings.AUTH_USER_MODEL)),
                ('referee_preferences', models.ManyToManyField(blank=True, related_name='preferred_fixtures', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.venue')),
            ],
        ),
    ]
